extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - prettier

parser: 'vue-eslint-parser'
parserOptions:
  parser: "@typescript-eslint/parser"

rules:
  "vue/multi-word-component-names": off
