printWidth: 120                   # Specify the line length that the printer will wrap on
tabWidth: 2                       # Specify the number of spaces per indentation-level
useTabs: true                     # Indent lines with tabs instead of spaces
semi: true                        # Print semicolons at the ends of statements
bracketSpacing: true              # Print spaces between brackets in object literals
plugins:
  - "prettier-plugin-tailwindcss" # Add prettier-plugin-tailwindcss to the list of plugins
