/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TokenomicsImport } from './routes/tokenomics'
import { Route as RoadmapImport } from './routes/roadmap'
import { Route as PrivateAiImport } from './routes/private-ai'
import { Route as ApiImport } from './routes/api'
import { Route as IndexImport } from './routes/index'
import { Route as UseCasesUbisoftImport } from './routes/use-cases/ubisoft'
import { Route as UseCasesLiberclawResearchAgentImport } from './routes/use-cases/liberclaw-research-agent'
import { Route as UseCasesLiberclawPersonalAssistantImport } from './routes/use-cases/liberclaw-personal-assistant'
import { Route as UseCasesLiberclawCodeReviewImport } from './routes/use-cases/liberclaw-code-review'
import { Route as UseCasesGenlayerImport } from './routes/use-cases/genlayer'

// Create/Update Routes

const TokenomicsRoute = TokenomicsImport.update({
  id: '/tokenomics',
  path: '/tokenomics',
  getParentRoute: () => rootRoute,
} as any)

const RoadmapRoute = RoadmapImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRoute,
} as any)

const PrivateAiRoute = PrivateAiImport.update({
  id: '/private-ai',
  path: '/private-ai',
  getParentRoute: () => rootRoute,
} as any)

const ApiRoute = ApiImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UseCasesUbisoftRoute = UseCasesUbisoftImport.update({
  id: '/use-cases/ubisoft',
  path: '/use-cases/ubisoft',
  getParentRoute: () => rootRoute,
} as any)

const UseCasesLiberclawResearchAgentRoute =
  UseCasesLiberclawResearchAgentImport.update({
    id: '/use-cases/liberclaw-research-agent',
    path: '/use-cases/liberclaw-research-agent',
    getParentRoute: () => rootRoute,
  } as any)

const UseCasesLiberclawPersonalAssistantRoute =
  UseCasesLiberclawPersonalAssistantImport.update({
    id: '/use-cases/liberclaw-personal-assistant',
    path: '/use-cases/liberclaw-personal-assistant',
    getParentRoute: () => rootRoute,
  } as any)

const UseCasesLiberclawCodeReviewRoute =
  UseCasesLiberclawCodeReviewImport.update({
    id: '/use-cases/liberclaw-code-review',
    path: '/use-cases/liberclaw-code-review',
    getParentRoute: () => rootRoute,
  } as any)

const UseCasesGenlayerRoute = UseCasesGenlayerImport.update({
  id: '/use-cases/genlayer',
  path: '/use-cases/genlayer',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiImport
      parentRoute: typeof rootRoute
    }
    '/private-ai': {
      id: '/private-ai'
      path: '/private-ai'
      fullPath: '/private-ai'
      preLoaderRoute: typeof PrivateAiImport
      parentRoute: typeof rootRoute
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapImport
      parentRoute: typeof rootRoute
    }
    '/tokenomics': {
      id: '/tokenomics'
      path: '/tokenomics'
      fullPath: '/tokenomics'
      preLoaderRoute: typeof TokenomicsImport
      parentRoute: typeof rootRoute
    }
    '/use-cases/genlayer': {
      id: '/use-cases/genlayer'
      path: '/use-cases/genlayer'
      fullPath: '/use-cases/genlayer'
      preLoaderRoute: typeof UseCasesGenlayerImport
      parentRoute: typeof rootRoute
    }
    '/use-cases/liberclaw-code-review': {
      id: '/use-cases/liberclaw-code-review'
      path: '/use-cases/liberclaw-code-review'
      fullPath: '/use-cases/liberclaw-code-review'
      preLoaderRoute: typeof UseCasesLiberclawCodeReviewImport
      parentRoute: typeof rootRoute
    }
    '/use-cases/liberclaw-personal-assistant': {
      id: '/use-cases/liberclaw-personal-assistant'
      path: '/use-cases/liberclaw-personal-assistant'
      fullPath: '/use-cases/liberclaw-personal-assistant'
      preLoaderRoute: typeof UseCasesLiberclawPersonalAssistantImport
      parentRoute: typeof rootRoute
    }
    '/use-cases/liberclaw-research-agent': {
      id: '/use-cases/liberclaw-research-agent'
      path: '/use-cases/liberclaw-research-agent'
      fullPath: '/use-cases/liberclaw-research-agent'
      preLoaderRoute: typeof UseCasesLiberclawResearchAgentImport
      parentRoute: typeof rootRoute
    }
    '/use-cases/ubisoft': {
      id: '/use-cases/ubisoft'
      path: '/use-cases/ubisoft'
      fullPath: '/use-cases/ubisoft'
      preLoaderRoute: typeof UseCasesUbisoftImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/private-ai': typeof PrivateAiRoute
  '/roadmap': typeof RoadmapRoute
  '/tokenomics': typeof TokenomicsRoute
  '/use-cases/genlayer': typeof UseCasesGenlayerRoute
  '/use-cases/liberclaw-code-review': typeof UseCasesLiberclawCodeReviewRoute
  '/use-cases/liberclaw-personal-assistant': typeof UseCasesLiberclawPersonalAssistantRoute
  '/use-cases/liberclaw-research-agent': typeof UseCasesLiberclawResearchAgentRoute
  '/use-cases/ubisoft': typeof UseCasesUbisoftRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/private-ai': typeof PrivateAiRoute
  '/roadmap': typeof RoadmapRoute
  '/tokenomics': typeof TokenomicsRoute
  '/use-cases/genlayer': typeof UseCasesGenlayerRoute
  '/use-cases/liberclaw-code-review': typeof UseCasesLiberclawCodeReviewRoute
  '/use-cases/liberclaw-personal-assistant': typeof UseCasesLiberclawPersonalAssistantRoute
  '/use-cases/liberclaw-research-agent': typeof UseCasesLiberclawResearchAgentRoute
  '/use-cases/ubisoft': typeof UseCasesUbisoftRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/private-ai': typeof PrivateAiRoute
  '/roadmap': typeof RoadmapRoute
  '/tokenomics': typeof TokenomicsRoute
  '/use-cases/genlayer': typeof UseCasesGenlayerRoute
  '/use-cases/liberclaw-code-review': typeof UseCasesLiberclawCodeReviewRoute
  '/use-cases/liberclaw-personal-assistant': typeof UseCasesLiberclawPersonalAssistantRoute
  '/use-cases/liberclaw-research-agent': typeof UseCasesLiberclawResearchAgentRoute
  '/use-cases/ubisoft': typeof UseCasesUbisoftRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/private-ai'
    | '/roadmap'
    | '/tokenomics'
    | '/use-cases/genlayer'
    | '/use-cases/liberclaw-code-review'
    | '/use-cases/liberclaw-personal-assistant'
    | '/use-cases/liberclaw-research-agent'
    | '/use-cases/ubisoft'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/private-ai'
    | '/roadmap'
    | '/tokenomics'
    | '/use-cases/genlayer'
    | '/use-cases/liberclaw-code-review'
    | '/use-cases/liberclaw-personal-assistant'
    | '/use-cases/liberclaw-research-agent'
    | '/use-cases/ubisoft'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/private-ai'
    | '/roadmap'
    | '/tokenomics'
    | '/use-cases/genlayer'
    | '/use-cases/liberclaw-code-review'
    | '/use-cases/liberclaw-personal-assistant'
    | '/use-cases/liberclaw-research-agent'
    | '/use-cases/ubisoft'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoute: typeof ApiRoute
  PrivateAiRoute: typeof PrivateAiRoute
  RoadmapRoute: typeof RoadmapRoute
  TokenomicsRoute: typeof TokenomicsRoute
  UseCasesGenlayerRoute: typeof UseCasesGenlayerRoute
  UseCasesLiberclawCodeReviewRoute: typeof UseCasesLiberclawCodeReviewRoute
  UseCasesLiberclawPersonalAssistantRoute: typeof UseCasesLiberclawPersonalAssistantRoute
  UseCasesLiberclawResearchAgentRoute: typeof UseCasesLiberclawResearchAgentRoute
  UseCasesUbisoftRoute: typeof UseCasesUbisoftRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRoute,
  PrivateAiRoute: PrivateAiRoute,
  RoadmapRoute: RoadmapRoute,
  TokenomicsRoute: TokenomicsRoute,
  UseCasesGenlayerRoute: UseCasesGenlayerRoute,
  UseCasesLiberclawCodeReviewRoute: UseCasesLiberclawCodeReviewRoute,
  UseCasesLiberclawPersonalAssistantRoute:
    UseCasesLiberclawPersonalAssistantRoute,
  UseCasesLiberclawResearchAgentRoute: UseCasesLiberclawResearchAgentRoute,
  UseCasesUbisoftRoute: UseCasesUbisoftRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/api",
        "/private-ai",
        "/roadmap",
        "/tokenomics",
        "/use-cases/genlayer",
        "/use-cases/liberclaw-code-review",
        "/use-cases/liberclaw-personal-assistant",
        "/use-cases/liberclaw-research-agent",
        "/use-cases/ubisoft"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/api": {
      "filePath": "api.tsx"
    },
    "/private-ai": {
      "filePath": "private-ai.tsx"
    },
    "/roadmap": {
      "filePath": "roadmap.tsx"
    },
    "/tokenomics": {
      "filePath": "tokenomics.tsx"
    },
    "/use-cases/genlayer": {
      "filePath": "use-cases/genlayer.tsx"
    },
    "/use-cases/liberclaw-code-review": {
      "filePath": "use-cases/liberclaw-code-review.tsx"
    },
    "/use-cases/liberclaw-personal-assistant": {
      "filePath": "use-cases/liberclaw-personal-assistant.tsx"
    },
    "/use-cases/liberclaw-research-agent": {
      "filePath": "use-cases/liberclaw-research-agent.tsx"
    },
    "/use-cases/ubisoft": {
      "filePath": "use-cases/ubisoft.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
